# Generated by Django 3.1.7 on 2021-03-21 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enxadrista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('idade', models.PositiveIntegerField()),
                ('pais', models.CharField(blank=True, max_length=3, null=True)),
                ('titulo', models.CharField(blank=True, max_length=2, null=True)),
                ('rating', models.CharField(blank=True, max_length=4, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JogadorFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=300)),
                ('jogador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banci_enxadrista', to='blog.enxadrista')),
            ],
        ),
    ]
