# Generated by Django 3.1.7 on 2021-03-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_enxadrista_jogadorfavorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogadorfavorito',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='enxadrista',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enxadrista',
            name='titulo',
            field=models.CharField(choices=[('GM', 'Grande Mestre'), ('MI', 'Mestre Internacional'), ('MI', 'Mestre FIDE'), ('CM', 'Candidato a Mestre'), ('MN', 'Mestre Nacional')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='jogadorfavorito',
            name='jogador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_favorito', to='blog.enxadrista'),
        ),
        migrations.AlterField(
            model_name='jogadorfavorito',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
