# Generated by Django 3.1.7 on 2021-03-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210321_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogadoresFavorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Jogador(a)', max_length=250)),
                ('motivo', models.CharField(max_length=100)),
                ('jogador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_favorito', to='blog.enxadrista')),
            ],
        ),
        migrations.DeleteModel(
            name='JogadorFavorito',
        ),
    ]
